# Site settings
name: Green_m's blog
email: greenm.xxoo@gmail.com 
author: Green_m
url: https://green-m.github.io/
resume_site: http://weibo.com/u/2585957090
github: https://github.com/Green-m
baseurl: ""
description: Do things that others can't do.
meta_description: 
motto: The more know the more need to learn.
banner: Be Modesty.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Green_m
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : api.duoshuo.com
    duoshuo:
        short_name : __Green_m
    disqus :
        short_name : __Green_m
        layout: default
        comments: true
    # other options
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
