# Site settings
name: Green_m
email: suckmine180@hotmail.com
author: Green_m
url: https://green-m.github.io/
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/Green-m
baseurl: ""
description: Do things that others can't do.
meta_description: 
motto: The more know the more need to learn.
banner: Be Modesty.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Green_m
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light