# Site settings
name: Green_m's blog
title: Green_m's blog
email: root@green-m.me
author: Green_m
url: https://green-m.github.io/
resume_site: http://weibo.com/u/2585957090
github: https://github.com/Green-m
baseurl: ""
description: Do things that others can't do.
meta_description: pentest;Green-m;Metasploit;Security
motto: The more know the more need to learn.
banner: Be Modesty.
plugins: 
  - jekyll-sitemap
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Green_m
highlighter: rouge

# Build settings
markdown: kramdown


# gitalk
github_repo: Green-m.github.io
github_username: Green-m
github_admin: Green-m
gitalk_clientId: 5ebd5082cef1a44ea391
gitalk_clientSecret: 283bd6b6a75507dbe803025420e08704e60ab176

collections:
  essays:
    output: true
    permalink: /essays/:year/:month/:day/:title/
    #sort_by: date
    #reverse: true

FB:
  comments :
    provider : gitalk

#    provider : disqus 
#    disqus :
#        short_name : https-green-m-github-io
    # other options
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
